postfix:
  image: psd/postfix
  ports:
    - "25:25"
  container_name: mailrelay
  environment:
    - SMTP_LOGIN=user@psd401.net
    - SMTP_PASSWORD=Password1 
    - EXT_RELAY_HOST=psd401-net.mail.protection.outlook.com 
    - EXT_RELAY_PORT=25 
    - USE_TLS=yes 
    - TLS_VERIFY=encrypt 
    - ACCEPTED_NETWORKS="172.17.0.0/24 172.17.0.37/32" 
    - DESTINATION=psd401.net
